service: rcebackend

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs18.x
  region: "ap-south-1"
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  home:
    handler: src/handler.home
    events:
      - http:
          path: /
          method: get
          cors: true
  api:
    handler: src/handler.code
    events:
      - http:
          path: /api/code/execute
          method: post
          cors: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
