service: rce-backend

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    http: true
  httpApi:
    # metrics: true # Enable if you need
    cors: true

functions:
  app:
    handler: handler.handler
    # reservedConcurrency: 100
    events:
      - http:
          path: "/{proxy+}"
          method: "*"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
